### ISSUE TITLE
LanController V3

### ISSUE THREAD

**Issue by fabiotodesco** [kofec/domoticz-tinycontrol#2]
Hi, i tried with V3 but the result is:

Scritto da Hrvoje Niksic <hniksic@xemacs.org>.
Inviare segnalazioni di bug e suggerimenti a <bug-wget@gnu.org>.
Traceback (most recent call last):
  File "./tinycontrol.py", line 105, in <module>
    pagehandle = opener.open(urll)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: File not found

in ssh test 

and 

 2018-02-06 10:54:02.029 (LC02-V3) Calling message handler 'onHeartbeat'.
2018-02-06 10:54:02.030 (LC02-V3) onHeartbeat called
2018-02-06 10:54:02.031 (LC02-V3) isAlive status: True
2018-02-06 10:54:02.031 (LC02-V3) Connect via wget to website: 10.100.60.34 user: admin password: admin
2018-02-06 10:54:02.139 Error: (LC02-V3) 'onHeartbeat' failed 'CalledProcessError'.
2018-02-06 10:54:02.139 Error: (LC02-V3) ----> Line 451 in /home/pi/domoticz/plugins/domoticz-tinycontrol/plugin.py, function onHeartbeat
2018-02-06 10:54:02.139 Error: (LC02-V3) ----> Line 353 in /home/pi/domoticz/plugins/domoticz-tinycontrol/plugin.py, function onHeartbeat
2018-02-06 10:54:02.139 Error: (LC02-V3) ----> Line 316 in /usr/lib/python3.5/subprocess.py, function check_output
2018-02-06 10:54:02.139 Error: (LC02-V3) ----> Line 398 in /usr/lib/python3.5/subprocess.py, function run 

in Domoticz Log

Thanks

**Comment by kofec** [comment]
I have added initial support. You can try and let me know

**Comment by fabiotodesco** [comment]
Hi, i have tried it. It work,s but when i change the state of the switch (eth0) i have a error on state changes. If i wait when the plugins take the values in domoticz the change of switch retourn correct.

When i click the switch the domoticz log write:

2018-03-05 14:12:53.520 Error: (Lan_C_V3) 'onHeartbeat' failed 'TypeError':'attribute of type 'NoneType' is not callable'.
2018-03-05 14:12:53.520 Error: (Lan_C_V3) ----> Line 521 in /home/fabio/domoticz/plugins/domoticz-tinycontrol/plugin.py, function onHeartbeat
2018-03-05 14:12:53.520 Error: (Lan_C_V3) ----> Line 445 in /home/fabio/domoticz/plugins/domoticz-tinycontrol/plugin.py, function onHeartbeat
2018-03-05 14:12:53.520 Error: (Lan_C_V3) ----> Line 552 in /home/fabio/domoticz/plugins/domoticz-tinycontrol/plugin.py, function UpdateDevice

**Comment by kofec** [comment]
As I understand you mean out0 not eth0 ? If so I will take a look today evevening

**Comment by fabiotodesco** [comment]
Yes is it...Sorry i have another question...In this new release i have a problem with a Lancontroller V2.
Domoticz log sent me:
2018-04-05 16:30:03.462 (control01) Calling message handler 'onHeartbeat'.
2018-04-05 16:30:03.462 (control01) onHeartbeat called
2018-04-05 16:30:03.827 (control01) isAlive status: True
2018-04-05 16:30:03.827 (control01) Connect via wget to website: http://admin:admin@10.10.4.121/st0.xml
2018-04-05 16:30:05.061 (control01) 1 .... 4>1522945805
2018-04-05 16:30:05.062 (control01) st0.xml :
2018-04-05 16:30:05.062 (control01) out0 => 1
2018-04-05 16:30:05.062 (control01) out1 => 1
2018-04-05 16:30:05.062 (control01) out2 => 1
2018-04-05 16:30:05.062 (control01) out3 => 1
2018-04-05 16:30:05.062 (control01) out4 => 1
2018-04-05 16:30:05.062 (control01) out5 => 1
2018-04-05 16:30:05.062 (control01) out6 => 1
2018-04-05 16:30:05.062 (control01) di0 => up
2018-04-05 16:30:05.062 (control01) di1 => up
2018-04-05 16:30:05.062 (control01) di2 => up
2018-04-05 16:30:05.062 (control01) di3 => up
2018-04-05 16:30:05.062 (control01) ia0 => 320
2018-04-05 16:30:05.062 (control01) ia1 => 104
2018-04-05 16:30:05.062 (control01) ia2 => 0
2018-04-05 16:30:05.062 (control01) ia3 => 3
2018-04-05 16:30:05.062 (control01) ia4 => 419
2018-04-05 16:30:05.062 (control01) ia5 => 0
2018-04-05 16:30:05.062 (control01) ia6 => 23
2018-04-05 16:30:05.062 (control01) ia7 => -600
2018-04-05 16:30:05.062 (control01) ia8 => -600
2018-04-05 16:30:05.062 (control01) ia9 => -600
2018-04-05 16:30:05.062 (control01) ia10 => -600
2018-04-05 16:30:05.062 (control01) ia11 => -600
2018-04-05 16:30:05.062 (control01) ia12 => -600
2018-04-05 16:30:05.062 (control01) ia13 => 0
2018-04-05 16:30:05.062 (control01) ia14 => 0
2018-04-05 16:30:05.062 (control01) ia15 => 0
2018-04-05 16:30:05.062 (control01) ia16 => 0
2018-04-05 16:30:05.062 (control01) ia17 => 0
2018-04-05 16:30:05.062 (control01) ia18 => 0
2018-04-05 16:30:05.062 (control01) ia19 => 0
2018-04-05 16:30:05.062 (control01) freq => 5008
2018-04-05 16:30:05.062 (control01) duty => 500
2018-04-05 16:30:05.062 (control01) pwm => 0
2018-04-05 16:30:05.062 (control01) sec0 => 37
2018-04-05 16:30:05.062 (control01) sec1 => 4
2018-04-05 16:30:05.062 (control01) sec2 => 18
2018-04-05 16:30:05.062 (control01) sec3 => 28
2018-04-05 16:30:05.062 (control01) sec4 => 1522945805
2018-04-05 16:30:05.062 Error: (control01) 'onHeartbeat' failed 'TypeError':'attribute of type 'NoneType' is not callable'.
2018-04-05 16:30:05.062 Error: (control01) ----> Line 520 in /home/admindom/domoticz/plugins/domoticz-tinycontrol/plugin.py, function onHeartbeat
2018-04-05 16:30:05.062 Error: (control01) ----> Line 444 in /home/admindom/domoticz/plugins/domoticz-tinycontrol/plugin.py, function onHeartbeat
2018-04-05 16:30:05.062 Error: (control01) ----> Line 551 in /home/admindom/domoticz/plugins/domoticz-tinycontrol/plugin.py, function UpdateDevice

**Comment by fabiotodesco** [comment]
Hi kofec, ave you updates?

**Comment by kofec** [comment]
There will be but not now - I don't have time

**Comment by fabiotodesco** [comment]
hi kofec are this project dead? I Have a question, is possible send a command to domoticz in realtime when digital inputs state change?

Have you in mind to make some new version of this plugin? 

The new version of Lancontroller support mqtt and will be fantastic if you can made a new plugin that interface this on Domoticz

**Comment by kofec** [comment]
Hi, I don't have version 3 of Lancontroller. But feel free to contribute.

**Comment by snetekombinerke** [comment]
Hi, kofec 

Is there possible to you to add new fetures for lancontroller v3 plugin 

I would like to see power and energy output in domoticz panel.
I tried to add energy to you code, I had some succes as I put the name as voltage but if I write kwh,domoticz doesent recognise subtype.

Thanks in advance. 

This is part of a log from domoticz

2021-02-22 19:50:45.486 (LAN CONTROLER) st0.xml :
2021-02-22 19:50:45.486 (LAN CONTROLER) sec0 => 4
2021-02-22 19:50:45.486 (LAN CONTROLER) sec1 => 7
2021-02-22 19:50:45.486 (LAN CONTROLER) sec2 => 22
2021-02-22 19:50:45.486 (LAN CONTROLER) sec3 => 0
2021-02-22 19:50:45.486 (LAN CONTROLER) sec4 => 1614023444
2021-02-22 19:50:45.486 (LAN CONTROLER) out => 31
2021-02-22 19:50:45.486 (LAN CONTROLER) out0 => 1
2021-02-22 19:50:45.486 (LAN CONTROLER) out1 => 1
2021-02-22 19:50:45.486 (LAN CONTROLER) out2 => 1
2021-02-22 19:50:45.486 (LAN CONTROLER) out3 => 1
2021-02-22 19:50:45.486 (LAN CONTROLER) out4 => 1
2021-02-22 19:50:45.486 (LAN CONTROLER) out5 => 0
2021-02-22 19:50:45.486 (LAN CONTROLER) pwm => 0
2021-02-22 19:50:45.486 (LAN CONTROLER) inp1 => 2881
2021-02-22 19:50:45.487 (LAN CONTROLER) inp2 => 73
2021-02-22 19:50:45.487 (LAN CONTROLER) inp3 => 68
2021-02-22 19:50:45.487 (LAN CONTROLER) inp4 => 86
2021-02-22 19:50:45.487 (LAN CONTROLER) inp5 => 0
2021-02-22 19:50:45.487 (LAN CONTROLER) inp6 => 0
2021-02-22 19:50:45.487 (LAN CONTROLER) inpp1 => 285
2021-02-22 19:50:45.487 (LAN CONTROLER) inpp2 => 486
2021-02-22 19:50:45.487 (LAN CONTROLER) inpp3 => 594
2021-02-22 19:50:45.487 (LAN CONTROLER) inpp4 => 555
2021-02-22 19:50:45.487 (LAN CONTROLER) inpp5 => 0
2021-02-22 19:50:45.487 (LAN CONTROLER) inpp6 => 0
2021-02-22 19:50:45.487 (LAN CONTROLER) vin => 907
2021-02-22 19:50:45.487 (LAN CONTROLER) tem => 4900
2021-02-22 19:50:45.487 (LAN CONTROLER) ind => 15
2021-02-22 19:50:45.487 (LAN CONTROLER) dth0 => -600
2021-02-22 19:50:45.487 (LAN CONTROLER) dth1 => -600
2021-02-22 19:50:45.487 (LAN CONTROLER) ds1 => 70
2021-02-22 19:50:45.487 (LAN CONTROLER) ds2 => 443
2021-02-22 19:50:45.487 (LAN CONTROLER) ds3 => 253
2021-02-22 19:50:45.487 (LAN CONTROLER) ds4 => 197
2021-02-22 19:50:45.487 (LAN CONTROLER) ds5 => 172
2021-02-22 19:50:45.487 (LAN CONTROLER) ds6 => -600
2021-02-22 19:50:45.487 (LAN CONTROLER) ds7 => -600
2021-02-22 19:50:45.487 (LAN CONTROLER) ds8 => -600
2021-02-22 19:50:45.487 (LAN CONTROLER) power1 => 1093
2021-02-22 19:50:45.487 (LAN CONTROLER) power2 => 1343
2021-02-22 19:50:45.487 (LAN CONTROLER) power3 => 1242
2021-02-22 19:50:45.487 (LAN CONTROLER) power4 => 0
2021-02-22 19:50:45.487 (LAN CONTROLER) energy1 => 11239
2021-02-22 19:50:45.487 (LAN CONTROLER) energy2 => 10990
2021-02-22 19:50:45.487 (LAN CONTROLER) energy3 => 9858
2021-02-22 19:50:45.488 (LAN CONTROLER) energy4 => 0
2021-02-22 19:50:45.488 (LAN CONTROLER) pm1 => -1
2021-02-22 19:50:45.488 (LAN CONTROLER) pm2 => -1
2021-02-22 19:50:45.488 (LAN CONTROLER) pm4 => -1
2021-02-22 19:50:45.488 (LAN CONTROLER) pm10 => -1
2021-02-22 19:50:45.488 (LAN CONTROLER) diff1 => 0
